### ISSUE TITLE
Strange error message when loading data by gpload

### ISSUE THREAD

**Issue by LittleWuCoding** [greenplum-db/gpdb#9877]
greenplum version：6.1.0
uname -a 
Linux anls34 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Dec 21 15:44:02 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

There are three machine in the GP cluster：anls34(master)，anls33(segment)，anls37(segment)

question：
When gpload is used to import data on node anls34, the following errors are occasionally reported:
```
2020-04-03 15:28:18|INFO|started gpfdist -p 5092 -P 5102 -f "/data1/xxx.txt" -t 10
2020-04-03 15:28:18|INFO|reusing external staging table ext_xxx_error_gp
2020-04-03 15:28:18|ERROR|ERROR:  connection with gpfdist failed for "gpfdist://anls37:5092//data1/xxx.txt", effective url: "http://10.47.222.37:5092/data1//xxx.txt": error code = 111 (Connection refused);  (seg0 slice1 10.47.222.34:40000 pid=12784)
```
It's strange that gpload was started in anls34, but the error message said that the corresponding file could not be found in anls37 node. Please help us to have a look.
The configuration file of gpload is as follows:
```
VERSION: 1.0.0.1
GPLOAD:
   INPUT:
    - SOURCE:
         LOCAL_HOSTNAME:
           - 10.47.222.34
         PORT_RANGE: [5092,5102]
         FILE:
           - /data1/xxx.txt
    - COLUMNS:
        - usercode: varchar(36)
       ......
       - FORMAT: text
        - DELIMITER: '|'    
        - NULL_AS: ''    
        - QUOTE: '"'    
        - HEADER: false    
        - ERROR_LIMIT: 1000    
        - LOG_ERRORS: true    
       OUTPUT:    
        - TABLE: public.xxx_work_gp    
        - MODE: insert    
       PRELOAD:    
        - TRUNCATE: false    
        - REUSE_TABLES: true    
        - STAGING_TABLE: ext_xxx_error_gp
```
